name: autobangumi
description: 全自动追番工具
annotations:
  title: AutoBangumi
type: application
version: 1.0.6
apiVersion: v2
appVersion: 3.1.18
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: Caidy
    url: https://github.com/chencaidy
    email: chen@caidy.cc
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://www.autobangumi.org/
icon: https://raw.githubusercontent.com/EstrellaXD/Auto_Bangumi/main/webui/public/images/pwa-192.png
sources:
  - https://github.com/EstrellaXD/Auto_Bangumi
  - https://www.autobangumi.org/
keywords:
  - media
  - torrent
  - download
