npmNetwork:
  webPort: 31000
  httpPort: 31001
  httpsPort: 31002
  hostNetwork: false

npmStorage:
  data:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/data
  certs:
    type: hostPath
    hostPath: /mnt/{{ .Release.Name }}/certs
